# Generated by Django 2.1 on 2018-08-14 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('raza', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fechaDeNacimiento', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=pets.models.custom_upload_to)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('dueño', models.ManyToManyField(related_name='get_pets', to=settings.AUTH_USER_MODEL, verbose_name='Dueños')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
