# Generated by Django 2.1 on 2018-08-16 05:59

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_mascota_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pets.models.custom_upload_to, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fechaDeNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50, verbose_name='Raza'),
        ),
    ]
