# Generated by Django 2.1 on 2018-09-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20180909_2229'),
        ('pets', '0004_mascota_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('camara', models.CharField(max_length=20, verbose_name='Nombre')),
                ('estado', models.BooleanField(default='True')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Cliente', verbose_name='Dueño')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.Mascota', verbose_name='Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='TiposServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='servicios',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.TiposServicios'),
        ),
    ]
