# Generated by Django 2.1 on 2018-09-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20180910_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='dueño',
            new_name='dueno',
        ),
    ]
