# Generated by Django 2.1 on 2018-09-10 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0006_auto_20180910_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='dueno',
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='get_pets', to=settings.AUTH_USER_MODEL, verbose_name='Dueños'),
            preserve_default=False,
        ),
    ]
