# Generated by Django 2.1 on 2018-09-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20180909_2229'),
        ('pets', '0007_auto_20180910_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='veterinaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registration.Veterinaria', verbose_name='Veterinaria'),
            preserve_default=False,
        ),
    ]
