# Generated by Django 2.1 on 2018-09-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_servicios_veterinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2018-09-08 19:20:10.370114', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicios',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
