# Generated by Django 2.1 on 2018-09-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20180910_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'ordering': ['-created'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='tiposservicios',
            options={'ordering': ['-id'], 'verbose_name': 'Tipo de servicio', 'verbose_name_plural': 'Tipos de servicios'},
        ),
    ]
