# Generated by Django 2.1 on 2018-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20180910_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='camara',
            field=models.CharField(max_length=20, verbose_name='Camara'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='cliente',
            field=models.CharField(max_length=20, verbose_name='Cc dueño'),
        ),
    ]
