# Generated by Django 2.1 on 2018-09-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_auto_20180910_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='ip',
            field=models.CharField(default=1, max_length=20, verbose_name='Camara'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicios',
            name='camara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_servicios', to='pets.Camara'),
        ),
    ]
