# Generated by Django 2.1 on 2018-10-11 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0014_auto_20181011_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacionmascota',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creador anotacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotacionmascota',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2011-09-01T13:20:30', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotacionmascota',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
