# Generated by Django 2.1 on 2018-11-28 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_auto_20181011_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pets.Mascota', verbose_name='Mascota'),
        ),
    ]
