# Generated by Django 2.1 on 2018-11-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_auto_20181127_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='ip',
            field=models.CharField(max_length=150, verbose_name='Camara'),
        ),
    ]
