# Generated by Django 2.1 on 2018-12-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_auto_20181128_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('m', 'Mamífero'), ('p', 'Pez'), ('b', 'Ave'), ('a', 'Anfibios'), ('r', 'Reptil'), ('o', 'Otro')], max_length=1),
        ),
    ]
