# Generated by Django 2.1 on 2018-11-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180916_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'id', 'title'], 'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
    ]
