# Generated by Django 2.1 on 2018-08-07 20:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0004_remove_veterinanria_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veterinanria',
            new_name='Veterinaria',
        ),
    ]
