# Generated by Django 2.1 on 2018-08-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180807_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
