# Generated by Django 2.1 on 2018-08-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180807_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
