# Generated by Django 2.1 on 2018-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180811_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veterinaria',
            options={'verbose_name': 'Veterinaria', 'verbose_name_plural': 'Veterinarias'},
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='rut',
            field=models.IntegerField(blank=True, null=True, verbose_name='RUT'),
        ),
    ]
