# Generated by Django 2.1 on 2018-09-10 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20180908_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_v', to=settings.AUTH_USER_MODEL),
        ),
    ]
