# Generated by Django 2.1 on 2018-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20180909_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cc',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
