# Generated by Django 2.1 on 2018-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20180910_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaria',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT'),
        ),
    ]
