# Generated by Django 2.1 on 2018-11-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20180910_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaria',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
    ]
