# Generated by Django 2.1 on 2018-11-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20181122_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaria',
            name='latitud',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='longitud',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
